name: hi_bob
description: "Hi Bob App | Built With Flutter"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  basics: ^0.10.0
  cached_network_image: ^3.3.1
  copy_with_extension: ^5.0.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter_bloc: ^8.1.5
  flutter_image_compress: ^2.2.0
  get_it: ^7.7.0
  go_router: ^13.2.4
  http: ^1.2.1
  image_picker: ^1.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  meta: ^1.11.0
  mockito: ^5.4.4
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  scrollable_positioned_list: ^0.3.8
  share_plus: ^8.0.3
  sqflite: ^2.3.3
  url_launcher: ^6.2.6
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  wrapfit: ^0.1.0+1
  flutter_staggered_animations: ^1.1.1
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  pinput: ^4.0.0
  just_audio: ^0.9.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  go_router_builder: ^2.5.1
  mocktail: ^1.0.3
  sqflite_common_ffi: ^2.3.3
  copy_with_extension_gen: ^5.0.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/